server:
  port: 8189
  servlet:
    context-path: /shop
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=april-market
#    username: postgres
#    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        hibernate: error
        data: error
  file:
    path: logs
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

#jwt:
#  secret: hbavouefvouaeffvouebviuo2332432$l4j23our34ouht08sljccdflefb
